[package]
name = "synthcat"
version = "0.1.0"
edition = "2021"
description = "Programmable music synthesiser"

[dependencies]
clap = {version = "4.5", features = ["derive"]}
mlua = {version = "0.9", features = ["lua54"]}
sdl2 = "0.37.0"
